import { collection, doc, onSnapshot, orderBy, query, runTransaction, setDoc } from "firebase/firestore";
import { db } from "@/utils/firebase/client";
export type SupportMessage={id:string;sender:"visitor"|"operator";text:string;sentAt:string};
export type SupportConversation={id:string;visitorId:string;email:string;page:string;createdAt:string;lastMessageAt:string;lastMessage:string;messages:SupportMessage[]};
const now=()=>new Date().toISOString(); const conversations="support_conversations";
export function visitorId(){const key="bluecrest-logistics-support-visitor";let id=localStorage.getItem(key);if(!id){id=crypto.randomUUID();localStorage.setItem(key,id)}return id}
export async function recordVisit(id:string,page:string,email=""){const time=now();await setDoc(doc(db,"support_visits",id),{id,email,page,lastSeenAt:time,firstSeenAt:time},{merge:true})}
export function watchConversation(id:string,callback:(value:SupportConversation|null)=>void){return onSnapshot(doc(db,conversations,id),s=>callback(s.exists()?s.data() as SupportConversation:null))}
export async function sendVisitorMessage(id:string,text:string,page:string,email:string){const message:SupportMessage={id:crypto.randomUUID(),sender:"visitor",text:text.trim().slice(0,1500),sentAt:now()};if(!message.text)return;const ref=doc(db,conversations,id);await runTransaction(db,async tx=>{const snap=await tx.get(ref);const old=snap.exists() ? snap.data() as SupportConversation : null;tx.set(ref,{id,visitorId:id,email,page,createdAt:old?.createdAt??message.sentAt,lastMessageAt:message.sentAt,lastMessage:message.text,messages:[...(old?.messages??[]),message].slice(-100)})})}
export function watchSupportInbox(callback:(value:SupportConversation[])=>void){return onSnapshot(query(collection(db,conversations),orderBy("lastMessageAt","desc")),s=>callback(s.docs.map(d=>d.data() as SupportConversation)))}
export function watchVisits(callback:(value:{id:string;page:string;lastSeenAt:string}[])=>void){return onSnapshot(query(collection(db,"support_visits"),orderBy("lastSeenAt","desc")),s=>callback(s.docs.map(d=>d.data() as {id:string;page:string;lastSeenAt:string})))}
export async function sendOperatorMessage(id:string,text:string){const value=text.trim().slice(0,1500);if(!value)return;const message:SupportMessage={id:crypto.randomUUID(),sender:"operator",text:value,sentAt:now()};const ref=doc(db,conversations,id);await runTransaction(db,async tx=>{const s=await tx.get(ref);if(!s.exists())throw Error("Conversation unavailable");const old=s.data() as SupportConversation;tx.update(ref,{lastMessageAt:message.sentAt,lastMessage:value,messages:[...(old.messages??[]),message].slice(-100)})})}
export function watchOperatorStatus(callback:(online:boolean)=>void){return onSnapshot(doc(db,"support_operator_status","primary"),s=>{const at=s.data()?.lastSeenAt;callback(Boolean(at&&Date.now()-new Date(at).getTime()<90000))})}
export async function markOperatorOnline(email:string){await setDoc(doc(db,"support_operator_status","primary"),{email,lastSeenAt:now()})}
